//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_GStore.ReferenciaProductos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Producto", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Carrito> TB_CarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APP_MVC_GStore.ReferenciaProductos.TB_Categoria TB_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_DetalleComprobante> TB_DetalleComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomProdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Carrito> TB_Carrito {
            get {
                return this.TB_CarritoField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_CarritoField, value) != true)) {
                    this.TB_CarritoField = value;
                    this.RaisePropertyChanged("TB_Carrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APP_MVC_GStore.ReferenciaProductos.TB_Categoria TB_Categoria {
            get {
                return this.TB_CategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_CategoriaField, value) != true)) {
                    this.TB_CategoriaField = value;
                    this.RaisePropertyChanged("TB_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_DetalleComprobante> TB_DetalleComprobante {
            get {
                return this.TB_DetalleComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_DetalleComprobanteField, value) != true)) {
                    this.TB_DetalleComprobanteField = value;
                    this.RaisePropertyChanged("TB_DetalleComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.descripcionField, value) != true)) {
                    this.descripcionField = value;
                    this.RaisePropertyChanged("descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                if ((this.estadoField.Equals(value) != true)) {
                    this.estadoField = value;
                    this.RaisePropertyChanged("estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string foto {
            get {
                return this.fotoField;
            }
            set {
                if ((object.ReferenceEquals(this.fotoField, value) != true)) {
                    this.fotoField = value;
                    this.RaisePropertyChanged("foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProd {
            get {
                return this.idProdField;
            }
            set {
                if ((this.idProdField.Equals(value) != true)) {
                    this.idProdField = value;
                    this.RaisePropertyChanged("idProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomProd {
            get {
                return this.nomProdField;
            }
            set {
                if ((object.ReferenceEquals(this.nomProdField, value) != true)) {
                    this.nomProdField = value;
                    this.RaisePropertyChanged("nomProd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Categoria", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Producto> TB_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Producto> TB_Producto {
            get {
                return this.TB_ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ProductoField, value) != true)) {
                    this.TB_ProductoField = value;
                    this.RaisePropertyChanged("TB_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomCategoria {
            get {
                return this.nomCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.nomCategoriaField, value) != true)) {
                    this.nomCategoriaField = value;
                    this.RaisePropertyChanged("nomCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Carrito", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_Carrito : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APP_MVC_GStore.ReferenciaProductos.TB_Producto TB_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> cantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCarritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idprodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APP_MVC_GStore.ReferenciaProductos.TB_Producto TB_Producto {
            get {
                return this.TB_ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ProductoField, value) != true)) {
                    this.TB_ProductoField = value;
                    this.RaisePropertyChanged("TB_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> cantidad {
            get {
                return this.cantidadField;
            }
            set {
                if ((this.cantidadField.Equals(value) != true)) {
                    this.cantidadField = value;
                    this.RaisePropertyChanged("cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCarrito {
            get {
                return this.idCarritoField;
            }
            set {
                if ((this.idCarritoField.Equals(value) != true)) {
                    this.idCarritoField = value;
                    this.RaisePropertyChanged("idCarrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idprod {
            get {
                return this.idprodField;
            }
            set {
                if ((this.idprodField.Equals(value) != true)) {
                    this.idprodField = value;
                    this.RaisePropertyChanged("idprod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_DetalleComprobante", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_DetalleComprobante : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APP_MVC_GStore.ReferenciaProductos.TB_ComprobantePago TB_ComprobantePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APP_MVC_GStore.ReferenciaProductos.TB_Producto TB_ProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numDetalleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APP_MVC_GStore.ReferenciaProductos.TB_ComprobantePago TB_ComprobantePago {
            get {
                return this.TB_ComprobantePagoField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ComprobantePagoField, value) != true)) {
                    this.TB_ComprobantePagoField = value;
                    this.RaisePropertyChanged("TB_ComprobantePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APP_MVC_GStore.ReferenciaProductos.TB_Producto TB_Producto {
            get {
                return this.TB_ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ProductoField, value) != true)) {
                    this.TB_ProductoField = value;
                    this.RaisePropertyChanged("TB_Producto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                if ((this.idComprobanteField.Equals(value) != true)) {
                    this.idComprobanteField = value;
                    this.RaisePropertyChanged("idComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProducto {
            get {
                return this.idProductoField;
            }
            set {
                if ((this.idProductoField.Equals(value) != true)) {
                    this.idProductoField = value;
                    this.RaisePropertyChanged("idProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numDetalle {
            get {
                return this.numDetalleField;
            }
            set {
                if ((this.numDetalleField.Equals(value) != true)) {
                    this.numDetalleField = value;
                    this.RaisePropertyChanged("numDetalle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_ComprobantePago", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_ComprobantePago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinatarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCliField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_DetalleComprobante> TB_DetalleComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APP_MVC_GStore.ReferenciaProductos.TB_Usuario TB_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> fechaCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idComprobanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destinatario {
            get {
                return this.DestinatarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinatarioField, value) != true)) {
                    this.DestinatarioField = value;
                    this.RaisePropertyChanged("Destinatario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCli {
            get {
                return this.NombreCliField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCliField, value) != true)) {
                    this.NombreCliField = value;
                    this.RaisePropertyChanged("NombreCli");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_DetalleComprobante> TB_DetalleComprobante {
            get {
                return this.TB_DetalleComprobanteField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_DetalleComprobanteField, value) != true)) {
                    this.TB_DetalleComprobanteField = value;
                    this.RaisePropertyChanged("TB_DetalleComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APP_MVC_GStore.ReferenciaProductos.TB_Usuario TB_Usuario {
            get {
                return this.TB_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_UsuarioField, value) != true)) {
                    this.TB_UsuarioField = value;
                    this.RaisePropertyChanged("TB_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                if ((this.fechaField.Equals(value) != true)) {
                    this.fechaField = value;
                    this.RaisePropertyChanged("fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechaCompra {
            get {
                return this.fechaCompraField;
            }
            set {
                if ((this.fechaCompraField.Equals(value) != true)) {
                    this.fechaCompraField = value;
                    this.RaisePropertyChanged("fechaCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idComprobante {
            get {
                return this.idComprobanteField;
            }
            set {
                if ((this.idComprobanteField.Equals(value) != true)) {
                    this.idComprobanteField = value;
                    this.RaisePropertyChanged("idComprobante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Usuario", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_ComprobantePago> TB_ComprobantePagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Direcciones> TB_DireccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string celularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> codigoactivacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> emailverficiadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_ComprobantePago> TB_ComprobantePago {
            get {
                return this.TB_ComprobantePagoField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_ComprobantePagoField, value) != true)) {
                    this.TB_ComprobantePagoField = value;
                    this.RaisePropertyChanged("TB_ComprobantePago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Direcciones> TB_Direcciones {
            get {
                return this.TB_DireccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_DireccionesField, value) != true)) {
                    this.TB_DireccionesField = value;
                    this.RaisePropertyChanged("TB_Direcciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidoField, value) != true)) {
                    this.apellidoField = value;
                    this.RaisePropertyChanged("apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string celular {
            get {
                return this.celularField;
            }
            set {
                if ((object.ReferenceEquals(this.celularField, value) != true)) {
                    this.celularField = value;
                    this.RaisePropertyChanged("celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> codigoactivacion {
            get {
                return this.codigoactivacionField;
            }
            set {
                if ((this.codigoactivacionField.Equals(value) != true)) {
                    this.codigoactivacionField = value;
                    this.RaisePropertyChanged("codigoactivacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contra {
            get {
                return this.contraField;
            }
            set {
                if ((object.ReferenceEquals(this.contraField, value) != true)) {
                    this.contraField = value;
                    this.RaisePropertyChanged("contra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> emailverficiado {
            get {
                return this.emailverficiadoField;
            }
            set {
                if ((this.emailverficiadoField.Equals(value) != true)) {
                    this.emailverficiadoField = value;
                    this.RaisePropertyChanged("emailverficiado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TB_Direcciones", Namespace="http://schemas.datacontract.org/2004/07/APP_MVC_ServicioWCF.Model")]
    [System.SerializableAttribute()]
    public partial class TB_Direcciones : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private APP_MVC_GStore.ReferenciaProductos.TB_Usuario TB_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomCiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomDireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nomDistritoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public APP_MVC_GStore.ReferenciaProductos.TB_Usuario TB_Usuario {
            get {
                return this.TB_UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TB_UsuarioField, value) != true)) {
                    this.TB_UsuarioField = value;
                    this.RaisePropertyChanged("TB_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idDireccion {
            get {
                return this.idDireccionField;
            }
            set {
                if ((this.idDireccionField.Equals(value) != true)) {
                    this.idDireccionField = value;
                    this.RaisePropertyChanged("idDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomCiudad {
            get {
                return this.nomCiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.nomCiudadField, value) != true)) {
                    this.nomCiudadField = value;
                    this.RaisePropertyChanged("nomCiudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDireccion {
            get {
                return this.nomDireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.nomDireccionField, value) != true)) {
                    this.nomDireccionField = value;
                    this.RaisePropertyChanged("nomDireccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDistrito {
            get {
                return this.nomDistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.nomDistritoField, value) != true)) {
                    this.nomDistritoField = value;
                    this.RaisePropertyChanged("nomDistrito");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaProductos.IServicioProductos")]
    public interface IServicioProductos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/Productos", ReplyAction="http://tempuri.org/IServicioProductos/ProductosResponse")]
        System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Producto> Productos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/Productos", ReplyAction="http://tempuri.org/IServicioProductos/ProductosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Producto>> ProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/InsertaProducto", ReplyAction="http://tempuri.org/IServicioProductos/InsertaProductoResponse")]
        void InsertaProducto(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/InsertaProducto", ReplyAction="http://tempuri.org/IServicioProductos/InsertaProductoResponse")]
        System.Threading.Tasks.Task InsertaProductoAsync(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/ActualizaProducto", ReplyAction="http://tempuri.org/IServicioProductos/ActualizaProductoResponse")]
        void ActualizaProducto(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/ActualizaProducto", ReplyAction="http://tempuri.org/IServicioProductos/ActualizaProductoResponse")]
        System.Threading.Tasks.Task ActualizaProductoAsync(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/EliminaProducto", ReplyAction="http://tempuri.org/IServicioProductos/EliminaProductoResponse")]
        void EliminaProducto(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProductos/EliminaProducto", ReplyAction="http://tempuri.org/IServicioProductos/EliminaProductoResponse")]
        System.Threading.Tasks.Task EliminaProductoAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProductosChannel : APP_MVC_GStore.ReferenciaProductos.IServicioProductos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProductosClient : System.ServiceModel.ClientBase<APP_MVC_GStore.ReferenciaProductos.IServicioProductos>, APP_MVC_GStore.ReferenciaProductos.IServicioProductos {
        
        public ServicioProductosClient() {
        }
        
        public ServicioProductosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProductosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProductosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Producto> Productos() {
            return base.Channel.Productos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<APP_MVC_GStore.ReferenciaProductos.TB_Producto>> ProductosAsync() {
            return base.Channel.ProductosAsync();
        }
        
        public void InsertaProducto(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj) {
            base.Channel.InsertaProducto(obj);
        }
        
        public System.Threading.Tasks.Task InsertaProductoAsync(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj) {
            return base.Channel.InsertaProductoAsync(obj);
        }
        
        public void ActualizaProducto(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj) {
            base.Channel.ActualizaProducto(obj);
        }
        
        public System.Threading.Tasks.Task ActualizaProductoAsync(APP_MVC_GStore.ReferenciaProductos.TB_Producto obj) {
            return base.Channel.ActualizaProductoAsync(obj);
        }
        
        public void EliminaProducto(int id) {
            base.Channel.EliminaProducto(id);
        }
        
        public System.Threading.Tasks.Task EliminaProductoAsync(int id) {
            return base.Channel.EliminaProductoAsync(id);
        }
    }
}
