//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ComprobantePago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ComprobantePago()
        {
            this.TB_DetalleComprobante = new HashSet<TB_DetalleComprobante>();
        }
    
        public int idComprobante { get; set; }
        public System.DateTime fecha { get; set; }
        public int idUsuario { get; set; }
        public string NombreCli { get; set; }
        public Nullable<System.DateTime> fechaCompra { get; set; }
        public string Destinatario { get; set; }
    
        public virtual TB_Usuario TB_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DetalleComprobante> TB_DetalleComprobante { get; set; }
    }
}
