//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Carrito
    {
        public int idCarrito { get; set; }
        public Nullable<int> idprod { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual TB_Producto TB_Producto { get; set; }
    }
}
