//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DetalleComprobante
    {
        public int numDetalle { get; set; }
        public int idComprobante { get; set; }
        public int idProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual TB_ComprobantePago TB_ComprobantePago { get; set; }
        public virtual TB_Producto TB_Producto { get; set; }
    }
}
