//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Tarjetas
    {
        public int idTarjeta { get; set; }
        public int idUsuario { get; set; }
        public string nombreTitular { get; set; }
        public string apellidoTitular { get; set; }
        public string nroTarjeta { get; set; }
        public Nullable<System.DateTime> fechaExpiracion { get; set; }
        public string ccv { get; set; }
        public Nullable<int> saldo { get; set; }
    
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
