//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_Datos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Tarjetas
    {
        public int idTarjeta { get; set; }
        public int idUsuario { get; set; }
        public string nombreTitular { get; set; }
        public string apellidoTitular { get; set; }
        public string nroTarjeta { get; set; }
        public Nullable<System.DateTime> fechaExpiracion { get; set; }
        public string ccv { get; set; }
        public Nullable<int> saldo { get; set; }
    
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
