//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_ServicioWCF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Usuario()
        {
            this.TB_ComprobantePago = new HashSet<TB_ComprobantePago>();
            this.TB_Direcciones = new HashSet<TB_Direcciones>();
        }
    
        public int idUsuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public Nullable<bool> emailverficiado { get; set; }
        public Nullable<System.Guid> codigoactivacion { get; set; }
        public string contra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ComprobantePago> TB_ComprobantePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Direcciones> TB_Direcciones { get; set; }
    }
}
