//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_GStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DetalleComprobante
    {
        public int numDetalle { get; set; }
        public int idComprobante { get; set; }
        public int idProducto { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual TB_ComprobantePago TB_ComprobantePago { get; set; }
        public virtual TB_Producto TB_Producto { get; set; }
    }
}
