//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APP_MVC_GStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Direcciones
    {
        public int idDireccion { get; set; }
        public string nomDireccion { get; set; }
        public string nomDistrito { get; set; }
        public string nomCiudad { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
